In [1]:
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import CSVLogger
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.applications import ResNet50V2
import os
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import Sequence
from tensorflow.keras.preprocessing.image import load_img
import random 
import matplotlib.pyplot as plt

In [12]:
#Paths
Path_img = "C:/Users/SEBASTIAN/OneDrive - Universidad de los Andes/Documentos/img_aug/x_aug/"
Path_mask = "C:/Users/SEBASTIAN/OneDrive - Universidad de los Andes/Documentos/img_aug/y_aug/"
path_img_0 = "C:/Users/SEBASTIAN/OneDrive - Universidad de los Andes/Documentos/img_aug/x_aug/img_0_0.PNG"
path_mask_0 = "C:/Users/SEBASTIAN/OneDrive - Universidad de los Andes/Documentos/img_aug/y_aug/mask_0_0.PNG"

path_img_1 = "C:/Users/SEBASTIAN/OneDrive - Universidad de los Andes/Documentos/img_aug/x_aug/img_1_414.png"
path_mask_1 = "C:/Users/SEBASTIAN/OneDrive - Universidad de los Andes/Documentos/img_aug/y_aug/mask_1_414.png"

In [22]:
x = np.zeros((3,) + (480,640) + (3,), dtype="float32")
y = np.zeros((3,) + (480,640) + (1,), dtype="uint8")
img = load_img(path_img_0, target_size=(480,640))
mask = load_img(path_mask_0,target_size=(480,640),color_mode='grayscale')
mask = np.expand_dims(mask,2)
x[0] = img
y[0] = mask
print(x[0].shape)
print(y[0].shape)

(480, 640, 3)
(480, 640, 1)


In [23]:
mx = np.max(img)
img_norm_0 = (img/mx) + 1 #Normalize the images.
x[1] = img_norm_0
print("Imagen original")
print(x[0].min(),x[0].max())
print("Imagen normalizada una vez")
print(x[1].min(),x[1].max())
print("Mask shape")
print(y[0].min(),y[0].max())

Imagen original
15.0 243.0
Imagen normalizada una vez
1.0617284 2.0
Mask shape
0 7


In [26]:
x = np.zeros((3,) + (480,640) + (3,), dtype="float32")
y = np.zeros((3,) + (480,640) + (1,), dtype="uint8")
img = load_img(path_img_1, target_size=(480,640))
mask = load_img(path_mask_1,target_size=(480,640),color_mode='grayscale')
mask = np.expand_dims(mask,2)
x[0] = img
y[0] = mask
print(x[0].shape)
print(y[0].shape)

(480, 640, 3)
(480, 640, 1)


In [31]:
mx = np.max(img)
img_norm_0 = (img/mx) + 1 #Normalize the images.
x[1] = img_norm_0
print("Imagen original")
print(x[0].min(),x[0].max())
print("Imagen normalizada una vez")
print(x[1].min(),x[1].max())
print("Mask logits")
print(y[0].min(),y[0].max())

Imagen original
0.0 255.0
Imagen normalizada una vez
7.0 8.0
Mask logits
0 7


In [30]:
print(np.isnan(y[0]))

[[[False]
  [False]
  [False]
  ...
  [False]
  [False]
  [False]]

 [[False]
  [False]
  [False]
  ...
  [False]
  [False]
  [False]]

 [[False]
  [False]
  [False]
  ...
  [False]
  [False]
  [False]]

 ...

 [[False]
  [False]
  [False]
  ...
  [False]
  [False]
  [False]]

 [[False]
  [False]
  [False]
  ...
  [False]
  [False]
  [False]]

 [[False]
  [False]
  [False]
  ...
  [False]
  [False]
  [False]]]


In [1]:
from tensorflow.keras.preprocessing.image import load_img
import numpy as np

In [2]:
path = "C:/Users/SEBASTIAN/OneDrive - Universidad de los Andes/Documentos/img_aug/x_aug/img_0_0.png"

In [9]:
img = load_img(path)
img = np.array(img)
print(img.shape)
print(img[0:3,0:3,0])

(480, 640, 3)
[[224 224 224]
 [224 224 224]
 [224 224 224]]


In [8]:
img = img/255
print(img[0:3,0:3,1])

[[0.00350634 0.00350634 0.00350634]
 [0.00350634 0.00350634 0.00350634]
 [0.00350634 0.00350634 0.00350634]]


In [7]:
from PIL.Image import open

0.8784313725490196

In [13]:
def display(displey_list):
    for i in range(len(displey_list)):
        plt.subplot(1,len(displey_list),i+1)
        plt.imshow(displey_list[i])
    plt.show()